function cardReveal(){
    document.querySelector("#back").classList.add("hide")
    let randomImage = new Array();

    randomImage[0] = "cards/394.png"
    randomImage[1] = "cards/and_action.png"
    randomImage[2] = "cards/argument.png"
    randomImage[3] = "cards/big_o_vouge.png"
    randomImage[4] = "cards/category.png"
    randomImage[5] = "cards/chug_bros.png"
    randomImage[6] = "cards/dancing_queen.png"
    randomImage[7] = "cards/do_me.png"
    randomImage[8] = "cards/do_them.png"
    randomImage[9] = "cards/dreams.png"
    randomImage[10] = "cards/lipsync.png"
    randomImage[11] = "cards/youre_under_arrest.png"
    randomImage[12] = "cards/my_precius.png"
    randomImage[13] = "cards/you_drink_3.png"
    randomImage[14] = "cards/you_laugh_you_lose.png"
    randomImage[15] = "cards/drunk_or_kid.png"
    randomImage[16] = "cards/fess_up.png"
    randomImage[17] = "cards/give_3.png"
    randomImage[18] = "cards/twerk_off.png"
    randomImage[19] = "cards/wish.png"
    randomImage[20] = "cards/zzz.png"
    randomImage[21] = "cards/give_chug.png"
    randomImage[22] = "cards/going_viral.png"
    randomImage[23] = "cards/hate.png"
    randomImage[24] = "cards/i_dont_give_a_chug.png"
    randomImage[25] = "cards/make_up_group_truth.png"
    randomImage[26] = "cards/make_up_truth.png"
    randomImage[27] = "cards/make_up_dare.png"
    randomImage[28] = "cards/make_up_group_dare.png"
    randomImage[29] = "cards/if_you_were_ritch.png"
    randomImage[30] = "cards/immunity.png"
    randomImage[31] = "cards/insomnia.png"
    randomImage[32] = "cards/invisibility.png"
    randomImage[33] = "cards/kiss.png"
    randomImage[34] = "cards/lapdance.png"
    randomImage[35] = "cards/biligual.png" 
    randomImage[36] = "cards/not_as_think.png"
    randomImage[37] = "cards/not_that_innocent.png"
    randomImage[38] = "cards/positioning.png"
    randomImage[39] = "cards/red_flag.png"
    randomImage[40] = "cards/saly_mayte.png"
    randomImage[41] = "cards/shameless_plug.png"
    randomImage[42] = "cards/skal.png"
    randomImage[43] = "cards/sploosh.png"
    randomImage[44] = "cards/squat.png"
    randomImage[45] = "cards/story_time.png"
    randomImage[46] = "cards/suck_and_blow.png"
    randomImage[47] = "cards/survivor.png"
    randomImage[48] = "cards/try_hard.png"
    randomImage[49] = "cards/try_harder.png"
    randomImage[50] = "cards/uno_revers.png"
    randomImage[51] = "cards/we_come_in_peace.png"
    randomImage[52] = "cards/who_am_i.png"
    randomImage[53] = "cards/xfactor.png"
   
  
    
    let number = Math.floor(Math.random()*randomImage.length)

    return document.querySelector("#result").innerHTML = '<img src="'+randomImage[number]+'" />'
}